version: '3.8'

services:
  db:
    image: postgres:15
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test"]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file: .env.test

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    depends_on:
      db:
        condition: service_healthy
    command: ["make", "test"]
    env_file: .env.test
