version: '3.8'

services:
  db:
    image: postgres:15
    env_file: .env.dev
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - "5000:5000"
    depends_on:
      - db
    env_file: .env.dev
    volumes:
      - .:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      timeout: 3s
      retries: 3
    command: "make run-dev"

volumes:
  db_data:
