from typing import Protocol, Optional
from app.application.dtos.client_dto import ClientDTO
from app.infrastructure.models.client import Client

class ClientServiceProtocol(Protocol):
    def create_client(self, dto: ClientDTO) -> Client: ...
    def get_clients(self) -> list[Client]: ...
    def get_client_by_id(self, client_id: int) -> Optional[Client]: ...
    def update_client(self, client_id: int, dto: ClientDTO) -> Optional[Client]: ...
    def delete_client(self, client_id: int) -> bool: ...
